# Generated by Django 5.2 on 2025-05-25 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_transportcompany_trip_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_number',
            field=models.CharField(default=uuid.uuid4, max_length=36, null=True, unique=True),
        ),
    ]
